### ISSUE TITLE
Sharing iP code quality feedback [for @jhchee18]

### ISSUE THREAD

**Issue by nus-se-script** [jhchee18/ip#3]
@jhchee18 We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

Example from [`src/main/java/duke/task/Task.java` lines `12-12`](https://github.com/jhchee18/ip/blob/47789c2bf0c2713a0e929723357d248f914b8796/src/main/java/duke/task/Task.java#L12..L12):

```java

    private final boolean markDone;

``` 

**Suggestion:** Follow the given naming convention for boolean variables/methods (e.g., use a boolean-sounding prefix).You may ignore the above if you think the name already follows the convention (the script can report false positives in some cases)

### Aspect: Brace Style

Example from [`src/main/java/duke/Duke.java` lines `53-54`](https://github.com/jhchee18/ip/blob/47789c2bf0c2713a0e929723357d248f914b8796/src/main/java/duke/Duke.java#L53..L54):

```java

        }
        catch (DukeException e) {

```

Example from [`src/main/java/duke/Parser.java` lines `55-56`](https://github.com/jhchee18/ip/blob/47789c2bf0c2713a0e929723357d248f914b8796/src/main/java/duke/Parser.java#L55..L56):

```java

        }
        catch (ArrayIndexOutOfBoundsException ex) {

```

Example from [`src/main/java/duke/frontend/MainWindow.java` lines `76-77`](https://github.com/jhchee18/ip/blob/47789c2bf0c2713a0e929723357d248f914b8796/src/main/java/duke/frontend/MainWindow.java#L76..L77):

```java

        }
        catch (DukeException e) {

``` 

**Suggestion:** As specified by the coding standard, use egyptian style braces.

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

Example from [`src/main/java/duke/task/Task.java` lines `131-131`](https://github.com/jhchee18/ip/blob/47789c2bf0c2713a0e929723357d248f914b8796/src/main/java/duke/task/Task.java#L131..L131):

```java

        //return "[" + (this.isMarked() ? "X" : " ") + "]" + this.taskName + this.getDateAndTime() + "\n";

```

Example from [`src/main/java/duke/task/ToDo.java` lines `34-34`](https://github.com/jhchee18/ip/blob/47789c2bf0c2713a0e929723357d248f914b8796/src/main/java/duke/task/ToDo.java#L34..L34):

```java

        //return "[" + this.getTaskType() + "]" + super.toString();

``` 

**Suggestion:** Remove dead code from the codebase.

### Aspect: Method Length

Example from [`src/main/java/duke/Reminder.java` lines `72-120`](https://github.com/jhchee18/ip/blob/47789c2bf0c2713a0e929723357d248f914b8796/src/main/java/duke/Reminder.java#L72..L120):

```java

    private String getCountDown(Task task) {
        int year = 0;
        int month = 0;
        int day = 0;
        Period periodDate = this.nowDate.until(task.getDate());
        String periodString = periodDate.toString();
        int number = 0;
        for (int i = 0; i < periodString.length(); i++) {
            char c = periodString.charAt(i);

            switch (c) {
            case 'P':
                break;
            case 'Y':
                year = number;
                break;
            case 'M':
                month = number;
                break;
            case 'D':
                day = number;
                break;
            default:
                number = Character.getNumericValue(c);
                break;
            }
        }
        String countdownString = "";
        if (year != 0) {
            countdownString += year + " Year, ";
        }
        if (month != 0) {
            countdownString += month + " Month, ";
        }
        if (day != 0) {
            countdownString += day + " Day, ";
        }

        long periodMinutes = this.nowTime.until(task.getTime(), MINUTES);
        long hour = periodMinutes / MINUTES_IN_AN_HOUR;
        long minute = periodMinutes % MINUTES_IN_AN_HOUR;
        if (hour != 0) {
            countdownString += hour + " Hour, ";
        }
        if (minute != 0) {
            countdownString += minute + " Minute ";
        }
        return countdownString;
    }

```

Example from [`src/main/java/duke/command/AddCommand.java` lines `43-101`](https://github.com/jhchee18/ip/blob/47789c2bf0c2713a0e929723357d248f914b8796/src/main/java/duke/command/AddCommand.java#L43..L101):

```java

    public String execute(TaskList taskList, Ui ui, Storage storage) throws DukeException {
        try {
            String[] parts = fullCommand.split(" ", 0);
            String command = parts[0];
            if (parts.length == 1) {
                throw new DukeException("OOPS!!! The description of a task cannot be empty.\n");
            }
            String taskName = "";
            String dateString = "";
            String timeString = "";
            for (int i = 1; i < parts.length; i++) {
                if (parts[i].charAt(0) != '/') {
                    taskName += parts[i] + " ";
                } else {
                    dateString = parts[i + 1];
                    timeString = parts[i + 2];
                    break;
                }
            }

            LocalDate date = null;
            if (!dateString.equals("")) {
                date = validateDateString(dateString);
            }

            LocalTime time = null;
            if (!timeString.equals("")) {
                time = validateTimeString(timeString);
            }

            Task task = null;
            switch (command) {
            case "todo":
                task = new ToDo(taskName, date, time);
                break;
            case "deadline":
                task = new Deadline(taskName, date, time);
                break;
            case "event":
                task = new Event(taskName, date, time);
                break;
            }
            taskList.addTask(task);

            String list = "";
            for (Task t : taskList.getList()) {
                list += t.toString();
            }
            storage.write(list);

            assert task != null : "Task is null.";
            return "Got it. I've added this task:\n" + ui.beautyWrapTask(task)
                    + "\nNow you have " + taskList.getSize() + " tasks in the list.\n";

        } catch (DateTimeParseException ex) {
            throw new DukeException("Invalid date & time format. Please follow the format of date "
                    + "as \"YYYY-MM-DD\" and time as \"HHMM\".");
        }
    }

``` 

**Suggestion:** Consider applying [SLAP (and other abstraction mechanisms)](https://nus-cs2103-ay2223s1.github.io/website//se-book-adapted/chapters/codeQuality.html#guideline-maximise-readability) to shorten methods e.g., extract some code blocks into separate methods. You may ignore this suggestion if you think a longer method is justified in a particular case.

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/duke/Duke.java` lines `38-40`](https://github.com/jhchee18/ip/blob/47789c2bf0c2713a0e929723357d248f914b8796/src/main/java/duke/Duke.java#L38..L40):

```java

    /**
     * Initialise the Duke program.
     */

```

Example from [`src/main/java/duke/Duke.java` lines `44-47`](https://github.com/jhchee18/ip/blob/47789c2bf0c2713a0e929723357d248f914b8796/src/main/java/duke/Duke.java#L44..L47):

```java

    /**
     * You should have your own function to generate a response to user input.
     * Replace this stub with your completed method.
     */

```

Example from [`src/main/java/duke/Parser.java` lines `24-29`](https://github.com/jhchee18/ip/blob/47789c2bf0c2713a0e929723357d248f914b8796/src/main/java/duke/Parser.java#L24..L29):

```java

    /**
     * Split the fullCommand into smaller parts and decide which Command to be created and returned.
     *
     * @param fullCommand the whole command input by user.
     * @return the corresponding Command subclasses.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message (Subject Only)

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by jhchee18** [comment]
All solved
